name: "Marc Qualie's Blog"
description: "My personal tech blog and insights into the world"
url: "http://marcqualie.com"
environment: development
cdn_host: //d2t499cyah0mck.cloudfront.net

markdown: redcarpet
redcarpet:
  extensions: ['tables']
excerpt_separator: "\n\n"
pygments: true
paginate: 5
paginate_path: /posts/:num/
relative_permalinks: false
permalink: /:year/:month/:title
paginate_path: "posts/:num"
exclude:
 - bower.json
 - Gemfile
 - Gemfile.lock
 - Makefile

# Search
lunr_search:
  min_length: 3

# Assets
assets:
  sources:
   - _assets/css
   - _assets/js
   - _assets/images
   - _assets/vendor/font-awesome/fonts
   - _assets/vendor

# Analytics
analytics:
  google:
    id: UA-4472999-7
