name: "Marc Qualie's Blog"
description: "My personal tech blog and insights into the world"
url: "http://marcqualie.com"
environment: development

markdown: redcarpet
excerpt_separator: "\n\n"
pygments: true
paginate: 5
permalink: /:year/:month/:title
paginate_path: "posts/:num"
exclude:
 - import.php

# Search
lunr_search:
  min_length: 3

# Assets
assets:
  cache: true
  js_compressor:  uglifier
  css_compressor: sass
  sources:
   - _assets/css
   - _assets/js

# Analytics
analytics:
  google:
    id: UA-4472999-7
